version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "prom-client"
     groups:
       babel:
         patterns:
           - '@babel/*'
           - 'lint-staged'
        eslint:
          patterns:
            - 'eslint*'
            - prettier
        express:
          patterns:
            - 'express*'
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
