repository:
  name: express-api-template-oauth2
  topics: express, oauth2
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downlaods: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - "Actions / Lint (15.x)"
          - "Actions / Coverage (15.x)"
          - "CodeQL / Analyze (javascript)"
