name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: ['on hold', request]
body:
  - type: textarea
    id: what-should-happened
    attributes:
      label: What would you like to see happen?
      description: This is a markdown-friendly area, feel free to upload images
      placeholder: Tell us what you see!
      value: "It should make me cake!"
    validations:
      required: true
